### ISSUE TITLE
Generate button always on top - same design as publish button

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/app_lego-mosaic#2]
El botón “Generate” debería estar siempre visible, parecido al botón “Publicar” y con los estilos de ese botón, también.

**Comment by brazadas** [comment]
what about this issue? it is ok as it is now (in the footer -- always visible)?

![image](https://user-images.githubusercontent.com/1489570/89071920-44441600-d33d-11ea-894c-fe446e6b36f3.png)

**Comment by jpmarindiaz** [comment]
Perfecto, aproved by @marianaviro
